### ISSUE TITLE
pyb library?

### ISSUE THREAD

**Issue by kswain1** [micropython-IMU/micropython-fusion#1]
I am having a problem importing the pub library where I can I find it. Tried using pip, and didn't have any luck.

**Comment by kswain1** [comment]
I'm using python 2.7, and I'm not using a micro python board. I am using OS X YOSEMITE to filter information.

**Comment by kswain1** [comment]
I only need the pyb module to complete this method Integrate to yield quaternion. Is there any other way I can do the integration with another module besides pyb?

**Comment by turbinenreiter** [comment]
You will have to replace the pyb calls with calls to time: https://docs.python.org/2/library/time.html

**Comment by kswain1** [comment]
Yes I have added the time function to instead of pyb.
Do you know if this is similar function to pyb micros

import time 
def micros():
     return time.time()/1000000

def elapsed_micros(start_time):
      return time.time()/1000000 - start_time

If so, I am currently getting all zero's for my yaw, pitch, and roll,which is definitely wrong. 
What are some average angles to expect?

**Comment by peterhinch** [comment]
time.time() returns seconds so you need to multiply by 1000000 to get microseconds rather than divide.

**Comment by kswain1** [comment]
Thank you will try it in the next couple of hours to let you know the results, so we can close this issue.

**Comment by neep8** [comment]
Hi I won't have my computer until the end of the month... But I was looking at getting the IMU code working in python3 with a mpu6050. Like you I struggled to find the pyb library. Hope it works for you.

**Comment by kswain1** [comment]
Hey I believed the solutions works! I am getting results, but my next question is for the calibration function during the initial time does the algorithm start the position at (0,0,0) until the chip is moved? If so I am having problems with the calibration portion of the algorithm.

**Comment by turbinenreiter** [comment]
Make sure to share your patches.

**Comment by kswain1** [comment]
I believe everything is working. Patch Update 
import time 
def micros():
return time.time()*1000000

def elapsed_micros(start_time):
return time.time()*1000000 - start_time

replace these functions with pyb, and you should be ok.
