### ISSUE TITLE
imu = MPU6050('X'), what is 'X'

### ISSUE THREAD

**Issue by fanlessfan** [micropython-IMU/micropython-fusion#13]
Hello,

Could anyone explain how to define the I2C pin and id when call the MPU6050 function? I am trying to use MPU6050 on ESP32 in MicroPython. my i2c pin are 4 and 5 and the i2c address is 0x68.

thx

**Comment by peterhinch** [comment]
Please see [the docs](https://github.com/micropython-IMU/micropython-mpu9x50#methods). It represents the X or Y side of a Pyboard 1.x, but for other platforms (I quote):

 >  an initialised I2C object may be passed.

**Comment by fanlessfan** [comment]
Thank you @peterhinch for the information
