### ISSUE TITLE
[Use case] Is my data good ?

### ISSUE THREAD

**Issue by MasterHansCoding** [micropython-IMU/micropython-fusion#16]
Hello !

I took some data from my phone, and put it into a csv file [sensor_data.csv](https://github.com/micropython-IMU/micropython-fusion/files/7675455/sensor_data.csv). The sensor data looks like this : 

![image](https://user-images.githubusercontent.com/59942428/145193879-b0499f80-e29c-427d-ab15-04e20cf75ac3.png)
![image](https://user-images.githubusercontent.com/59942428/145193682-eb01dd5e-c335-4be0-a2d0-0d0303c52016.png)
![image](https://user-images.githubusercontent.com/59942428/145194010-57a4b68e-d25c-4359-920e-b3750614ff29.png)

I can already take the orientation but there's too much noise, so I'm hoping making the noise disappear with your code : 

![image](https://user-images.githubusercontent.com/59942428/145194618-594f574c-bfe7-4dae-ba22-6dd9b66bad01.png)

I made a code taking the data, applying the functions Fusion.calibrate(), and Fusion.update(), but the output isn't like my orientation data : 

```python
import csv
import matplotlib.pyplot as plt
import math
from fusion import Fusion
from math import radians

def timediff(t_new, t_old):
    dt = t_new - t_old
    return dt

class Getxyz:
    def __init__(self, L_comp_xyz):
        self.L_comp_xyz = L_comp_xyz
        self.i = -1

    def __call__(self):
        self.i += 1
        if self.i == len(self.L_comp_xyz):
            return False
        return self.L_comp_xyz[self.i]

class Stopfunc:
    def __init__(self, L):
        self.length = len(L)
        self.i = -1
    
    def __call__(self):
        self.i += 1
        if self.i == self.length - 1:
            return True
        else:
            return False


fuse = Fusion(timediff)

# Opening csv file, taking out header :
csv_name = "sensor_data.csv"
file = open(csv_name)
csvreader = csv.reader(file)
header = next(csvreader)
print(header)

L_time = []
L_orientation_azimuth = []
L_orientation_pitch = []
L_orientation_roll = []
L_accel_X = []
L_accel_Y = []
L_accel_Z = []
L_gyro_X = []
L_gyro_Y = []
L_gyro_Z = []
L_compass_X = []
L_compass_Y = []
L_compass_Z = []
L_comp_xyz = []

# Taking data :
rows = []
for row in csvreader:
    L_time.append(round(float(row[0]), 3))
    L_orientation_azimuth.append(round(float(row[1]), 3))
    L_orientation_pitch.append(round(float(row[2]), 3))
    L_orientation_roll.append(round(float(row[3]), 3))

    L_gyro_X.append(round(float(row[4]), 3))
    L_gyro_Y.append(round(float(row[5]), 3))
    L_gyro_Z.append(round(float(row[6]), 3))

    L_accel_X.append(round(float(row[7]), 3))
    L_accel_Y.append(round(float(row[8]), 3))
    L_accel_Z.append(round(float(row[9]), 3))

    L_compass_X.append(round(float(row[10]), 3))
    L_compass_Y.append(round(float(row[11]), 3))
    L_compass_Z.append(round(float(row[12]), 3))

    comp = (float(row[10]), float(row[11]), float(row[12]))
    L_comp_xyz.append(comp)

# Calibrating :
calibrate = False # Doesn't change the results ...
if calibrate:
    getxyz = Getxyz(L_comp_xyz)
    stopfunc = Stopfunc(L_comp_xyz)
    fuse.calibrate(getxyz, stopfunc)
    print("fuse.magbias : ", fuse.magbias)


# Applying the filter fuse.update() :
L_heading = []
L_pitch = []
L_roll = []

for i in range(len(L_time)):
    ts = L_time[i]
    acc = (L_accel_X[i], L_accel_Y[i], L_accel_Z[i])
    gyro = (L_gyro_X[i], L_gyro_Y[i], L_gyro_Z[i])
    comp = (L_compass_X[i], L_compass_Y[i], L_compass_Z[i])
    
    fuse.update(acc, gyro, comp, ts)

    L_heading.append(radians(fuse.heading))
    L_pitch.append(radians(fuse.pitch))
    L_roll.append(radians(fuse.roll))

# Compairing phone orientation with the filter's results on matplotlib :
display_results = True
if display_results:

    print("last time : ", L_time[-1])
    fig, axs = plt.subplots(3)
    axs[0].set_xlim(0, 100)
    axs[0].set_ylim(-math.pi, math.pi)

    axs[0].set_title('heading')
    line1 = axs[0].plot(L_time, L_orientation_azimuth, 'b-', label="phone orientation")
    line2 = axs[0].plot(L_time, L_heading, 'g-', label="fuse orientation")
    axs[0].set_ylabel("rad")

    axs[1].set_title('pitch')
    line1 = axs[1].plot(L_time, L_orientation_pitch, 'b-', label="phone orientation")
    line2 = axs[1].plot(L_time, L_pitch, 'g-', label="fuse orientation")
    axs[1].set_ylabel("rad")

    axs[2].set_title('roll')
    line1 = axs[2].plot(L_time, L_orientation_roll, 'b-', label="phone orientation")
    line2 = axs[2].plot(L_time, L_roll, 'g-', label="fuse orientation")
    axs[2].legend()
    axs[2].set_ylabel("rad")
    axs[2].set_xlabel("seconds")
    
    plt.show()

```
Results :
![image](https://user-images.githubusercontent.com/59942428/145198560-209ef6dd-89b4-45e0-9ad6-6acb9d91ade2.png)

Do you have any idea why heading, pitch and roll of fuse aren't following the expected orientation ?

This use case can be added to your repository if you like it.

BR

Loic

I used [kivy ](https://github.com/kivy/kivy), [plyer](https://github.com/kivy/plyer) and socket to get this data.

**Comment by peterhinch** [comment]
The fusion module is really intended for microcontrollers running MicroPython and connected to IMU chips running a realtime data stream. Your application is unusual - I haven't come across anyone using it in this way. You need to think hard about units and about the time variable.

The source data looks bizarre. Firstly the acceleration X data: the figure 10,000 is caused by gravity, but shows excursions below this figure without matching excursions above. I think Newton and Einstein would have something to say about that. The gyro X data is even odder: the asymmetry about zero implies that, for the duration of the test, you rotated at ever increasing speed.

I haven't time to study this in detail, but if the initial data contradicts basic physics I think all bets are off.
